export const CATEGORIES = [
  { id: 'birthday',    label: 'Birthday',     emoji: '🎂', count: 48 },
  { id: 'anniversary', label: 'Anniversary',  emoji: '💍', count: 32 },
  { id: 'chocolate',   label: 'Chocolate',    emoji: '🍫', count: 56 },
  { id: 'designer',    label: 'Designer',     emoji: '✨', count: 40 },
  { id: 'fruit',       label: 'Fruit Cakes',  emoji: '🍓', count: 28 },
  { id: 'wedding',     label: 'Wedding',      emoji: '👰', count: 22 },
  { id: 'kids',        label: 'Kids Cakes',   emoji: '🦄', count: 35 },
  { id: 'eggless',     label: 'Eggless',      emoji: '🌿', count: 44 },
  { id: 'photo',       label: 'Photo Cakes',  emoji: '📸', count: 19 },
  { id: 'bento',       label: 'Bento Cakes',  emoji: '🎁', count: 24 },
  { id: 'heart',       label: 'Heart Shape',  emoji: '❤️', count: 18 },
  { id: 'pinata',      label: 'Pinata Cakes', emoji: '🎊', count: 15 },
  { id: 'jar',         label: 'Jar Cakes',    emoji: '🫙', count: 20 },
  { id: 'cupcakes',    label: 'Cupcakes',     emoji: '🧁', count: 38 },
  { id: 'pastries',    label: 'Pastries',     emoji: '🥐', count: 30 },
  { id: 'cheesecake',  label: 'Cheesecake',   emoji: '🍰', count: 16 },
  { id: 'dry',         label: 'Dry Cakes',    emoji: '🍮', count: 12 },
  { id: 'brownies',    label: 'Brownies',     emoji: '🍩', count: 14 },
];

export const CAKES = [
  // ── Chocolate ──────────────────────────────────────────
  { id: 1,  category: 'chocolate',  name: 'Belgian Chocolate Truffle', subtitle: 'Rich ganache with gold leaf',        price: 849,  originalPrice: 1099, discount: 23, rating: 4.9, reviews: 2847, deliveryTime: '60 min', emoji: '🍫', egg: 'Egg',     tag: 'BESTSELLER', weights: ['500g','1Kg','1.5Kg','2Kg'], serves: '6–8',  flavor: 'Dark Chocolate', desc: 'Indulgent Belgian chocolate layers with silky truffle ganache, finished with gold leaf and cocoa dusting. Our most beloved creation.',        ingredients: 'Belgian Dark Chocolate, Fresh Cream, Butter, Eggs, Flour, Sugar, Cocoa, Gold Leaf', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 2,  category: 'chocolate',  name: 'Ferrero Rocher Cake',       subtitle: 'Hazelnut choco crown',               price: 1149, originalPrice: 1399, discount: 18, rating: 4.9, reviews: 3124, deliveryTime: '60 min', emoji: '🎯', egg: 'Egg',     tag: 'PREMIUM',    weights: ['500g','1Kg','1.5Kg','2Kg'], serves: '8–10', flavor: 'Hazelnut',       desc: 'Crowned with authentic Ferrero Rocher chocolates on a rich hazelnut sponge with chocolate ganache.',                                         ingredients: 'Ferrero Rocher, Hazelnut, Dark Chocolate, Cream, Eggs', allergens: 'Gluten, Dairy, Eggs, Nuts', storage: 'Refrigerate. Best within 2 days.' },
  { id: 3,  category: 'chocolate',  name: 'Choco Lava Cake',           subtitle: 'Molten dark center',                 price: 699,  originalPrice: 899,  discount: 22, rating: 4.8, reviews: 1456, deliveryTime: '45 min', emoji: '🌋', egg: 'Egg',     tag: 'POPULAR',    weights: ['500g','1Kg'],               serves: '4–6',  flavor: 'Dark Chocolate', desc: 'Warm molten dark chocolate center oozing out of a perfectly baked soft sponge. Best served fresh.',                                          ingredients: 'Dark Chocolate, Butter, Eggs, Flour, Sugar', allergens: 'Gluten, Dairy, Eggs', storage: 'Best consumed fresh.' },
  { id: 4,  category: 'chocolate',  name: 'Dark Fantasy Chocolate',    subtitle: '70% dark cacao layers',              price: 749,  originalPrice: 999,  discount: 25, rating: 4.8, reviews: 1923, deliveryTime: '90 min', emoji: '🌑', egg: 'Egg',     tag: 'NEW',        weights: ['500g','1Kg','1.5Kg'],       serves: '4–6',  flavor: 'Dark Chocolate', desc: 'Deep, intense dark chocolate with 70% cacao sponge layers and bitter cocoa cream. For true chocolate lovers.',                               ingredients: 'Dark Chocolate 70%, Cream, Butter, Flour, Cocoa', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 5,  category: 'chocolate',  name: 'Chocolate Overload Cake',   subtitle: 'Triple chocolate heaven',            price: 999,  originalPrice: 1249, discount: 20, rating: 4.9, reviews: 2101, deliveryTime: '90 min', emoji: '🍪', egg: 'Egg',     tag: 'TRENDING',   weights: ['1Kg','1.5Kg','2Kg'],        serves: '8–10', flavor: 'Triple Choco',   desc: 'Three layers of white, milk and dark chocolate sponge, glazed with chocolate and loaded with chocolate shavings.',                           ingredients: 'Dark, Milk & White Chocolate, Cream, Butter, Eggs', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  // ── Birthday ────────────────────────────────────────────
  { id: 6,  category: 'birthday',   name: 'Rainbow Birthday Cake',     subtitle: '6 colorful layered surprise',        price: 949,  originalPrice: 1199, discount: 21, rating: 4.8, reviews: 1547, deliveryTime: '90 min', emoji: '🌈', egg: 'Egg',     tag: 'POPULAR',    weights: ['500g','1Kg','1.5Kg','2Kg'], serves: '8–10', flavor: 'Vanilla',        desc: 'Six vibrant rainbow layers with colorful buttercream, confetti sprinkles, and birthday candles. Pure celebration magic.',                   ingredients: 'Flour, Sugar, Butter, Eggs, Food Colors, Buttercream', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 7,  category: 'birthday',   name: 'Sprinkles Party Cake',      subtitle: 'Funfetti surprise inside',           price: 799,  originalPrice: 999,  discount: 20, rating: 4.7, reviews: 1102, deliveryTime: '90 min', emoji: '🎉', egg: 'Egg',     tag: 'FUN',        weights: ['500g','1Kg','1.5Kg'],       serves: '6–8',  flavor: 'Vanilla',        desc: 'Classic vanilla sponge studded with rainbow sprinkles throughout, frosted with colorful buttercream and loaded with party vibes.',          ingredients: 'Flour, Sugar, Butter, Eggs, Rainbow Sprinkles, Buttercream', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 8,  category: 'birthday',   name: 'Black Forest Birthday',     subtitle: 'Cherry & cream classic',             price: 849,  originalPrice: 1099, discount: 23, rating: 4.8, reviews: 2234, deliveryTime: '60 min', emoji: '🍒', egg: 'Egg',     tag: 'CLASSIC',    weights: ['500g','1Kg','1.5Kg','2Kg'], serves: '6–10', flavor: 'Chocolate Cherry', desc: 'Classic German Black Forest with chocolate sponge, kirsch-soaked cherries, fresh cream and chocolate shavings.',                         ingredients: 'Dark Chocolate, Cherries, Fresh Cream, Kirsch, Flour', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 9,  category: 'birthday',   name: 'Premium Celebration Cake',  subtitle: 'Gold leaf tiered elegance',          price: 1299, originalPrice: 1599, discount: 19, rating: 4.9, reviews: 892,  deliveryTime: '60 min', emoji: '🏆', egg: 'Egg',     tag: 'PREMIUM',    weights: ['1Kg','1.5Kg','2Kg'],        serves: '10–14', flavor: 'Vanilla Strawberry', desc: 'Tiered celebration with fresh roses, gold leaf, and personalized message. Our most premium birthday offering.',                         ingredients: 'Flour, Strawberry, Gold Leaf, Edible Flowers, Cream', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  // ── Anniversary ─────────────────────────────────────────
  { id: 10, category: 'anniversary', name: 'Red Velvet Love Cake',     subtitle: 'Heart-shaped cream cheese dream',    price: 899,  originalPrice: 1149, discount: 22, rating: 4.9, reviews: 2234, deliveryTime: '60 min', emoji: '❤️', egg: 'Egg',     tag: 'BESTSELLER', weights: ['500g','1Kg','1.5Kg','2Kg'], serves: '6–10', flavor: 'Red Velvet',     desc: 'Romantic heart-shaped red velvet with cream cheese frosting and hand-piped velvet roses.',                                                   ingredients: 'Red Velvet Flour, Cocoa, Cream Cheese, Butter, Buttermilk', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 11, category: 'anniversary', name: 'Romantic Rose Cake',       subtitle: 'Hundreds of buttercream roses',      price: 1099, originalPrice: 1349, discount: 19, rating: 4.8, reviews: 1102, deliveryTime: '90 min', emoji: '🌹', egg: 'Egg',     tag: 'ROMANTIC',   weights: ['500g','1Kg','1.5Kg'],       serves: '6–8',  flavor: 'Rose Vanilla',   desc: 'Delicate vanilla sponge adorned with hundreds of hand-piped buttercream roses in soft pink and ivory.',                                     ingredients: 'Vanilla Sponge, Buttercream, Rose Essence, Edible Roses', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 12, category: 'anniversary', name: 'Golden Heart Anniversary', subtitle: 'Gold leaf romantic creation',        price: 1399, originalPrice: 1699, discount: 18, rating: 4.9, reviews: 678,  deliveryTime: '2 hrs',  emoji: '💛', egg: 'Egg',     tag: 'LUXURY',     weights: ['1Kg','1.5Kg','2Kg'],        serves: '8–12', flavor: 'Champagne Vanilla', desc: 'Champagne-infused vanilla layers with gold leaf hearts and a personalized romantic message.',                                              ingredients: 'Champagne, Vanilla Bean, Gold Leaf, Edible Hearts, Flour', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 13, category: 'anniversary', name: 'Luxury Floral Cake',       subtitle: 'Fresh edible floral art',            price: 1599, originalPrice: 1999, discount: 20, rating: 5.0, reviews: 412,  deliveryTime: '3 hrs',  emoji: '💐', egg: 'Egg',     tag: 'DESIGNER',   weights: ['1Kg','1.5Kg','2Kg'],        serves: '8–12', flavor: 'Lychee Rose',    desc: 'A floral masterpiece with fresh edible flowers, lychee cream and rose essence. Handcrafted to perfection.',                                  ingredients: 'Edible Flowers, Lychee Cream, Rose Essence, Vanilla Sponge', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  // ── Kids ────────────────────────────────────────────────
  { id: 14, category: 'kids',        name: 'Unicorn Magic Cake',       subtitle: 'Pastel rainbow with glitter horn',   price: 999,  originalPrice: 1249, discount: 20, rating: 4.9, reviews: 1876, deliveryTime: '90 min', emoji: '🦄', egg: 'Egg',     tag: 'KIDS FAV',   weights: ['500g','1Kg','1.5Kg'],       serves: '6–8',  flavor: 'Strawberry',     desc: 'Magical unicorn with pastel buttercream swirls, edible glitter, gold fondant horn. Every child\'s dream.',                                  ingredients: 'Strawberry Sponge, Buttercream, Edible Glitter, Fondant', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 15, category: 'kids',        name: 'Superhero Theme Cake',     subtitle: 'Action-packed fondant heroes',       price: 899,  originalPrice: 1099, discount: 18, rating: 4.7, reviews: 1254, deliveryTime: '90 min', emoji: '🦸', egg: 'Egg',     tag: 'POPULAR',    weights: ['500g','1Kg','1.5Kg'],       serves: '6–8',  flavor: 'Vanilla',        desc: 'Action-packed superhero cake with custom fondant characters and vibrant comic book colors.',                                                 ingredients: 'Vanilla Sponge, Fondant, Food Colors, Buttercream', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  { id: 16, category: 'kids',        name: 'Barbie Dream Cake',        subtitle: 'Pink princess doll cake',            price: 1099, originalPrice: 1349, discount: 19, rating: 4.8, reviews: 987,  deliveryTime: '2 hrs',  emoji: '💖', egg: 'Egg',     tag: 'TRENDING',   weights: ['1Kg','1.5Kg'],              serves: '8–10', flavor: 'Strawberry',     desc: 'Beautiful pink princess Barbie doll cake with ruffled fondant skirt and sparkling tiara.',                                                  ingredients: 'Strawberry Sponge, Pink Fondant, Edible Glitter', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  // ── Designer ────────────────────────────────────────────
  { id: 17, category: 'designer',    name: 'Marble Texture Cake',      subtitle: 'Handcrafted marble fondant art',     price: 1499, originalPrice: 1899, discount: 21, rating: 4.9, reviews: 756,  deliveryTime: '2 hrs',  emoji: '🔲', egg: 'Egg',     tag: 'DESIGNER',   weights: ['1Kg','1.5Kg','2Kg'],        serves: '8–12', flavor: 'Vanilla',        desc: 'Breathtaking marble-effect fondant with gold geometric accents. Every cake unique, handcrafted by master artisans.',                        ingredients: 'Fondant, Gold Luster Dust, Vanilla Sponge, Buttercream', allergens: 'Gluten, Dairy, Eggs', storage: 'Room temp 4hrs, refrigerate after.' },
  { id: 18, category: 'designer',    name: 'Gold Luxe Cake',           subtitle: '24k edible gold masterpiece',        price: 2499, originalPrice: 2999, discount: 17, rating: 5.0, reviews: 412,  deliveryTime: '3 hrs',  emoji: '👑', egg: 'Egg',     tag: 'LUXURY',     weights: ['1Kg','1.5Kg','2Kg','3Kg'],  serves: '10–16', flavor: 'Champagne',     desc: 'The pinnacle of luxury. Draped in 24k edible gold leaf with dark fondant base. A showstopper for any occasion.',                           ingredients: '24k Edible Gold Leaf, Dark Fondant, Champagne Cream, Vanilla Bean', allergens: 'Gluten, Dairy, Eggs', storage: 'Room temp 2hrs, refrigerate after.' },
  { id: 19, category: 'designer',    name: 'Minimal Korean Cake',      subtitle: 'Clean aesthetic bento style',        price: 1199, originalPrice: 1499, discount: 20, rating: 4.8, reviews: 634,  deliveryTime: '2 hrs',  emoji: '🎨', egg: 'Egg',     tag: 'TRENDING',   weights: ['500g','1Kg'],               serves: '4–8',  flavor: 'Matcha Vanilla', desc: 'Korean-inspired minimalist design with clean lines, soft pastel tones and delicate hand-painted details.',                                  ingredients: 'Matcha, Vanilla Bean, White Chocolate, Edible Paint', allergens: 'Gluten, Dairy, Eggs', storage: 'Refrigerate. Best within 2 days.' },
  // ── Eggless ─────────────────────────────────────────────
  { id: 20, category: 'eggless',     name: 'Eggless Choco Dream',      subtitle: '100% vegetarian indulgence',         price: 799,  originalPrice: 999,  discount: 20, rating: 4.7, reviews: 2341, deliveryTime: '60 min', emoji: '🌿', egg: 'Eggless', tag: 'EGGLESS',    weights: ['500g','1Kg','1.5Kg','2Kg'], serves: '6–8',  flavor: 'Chocolate',      desc: 'Same indulgent Belgian chocolate taste without eggs. 100% vegetarian and preservative-free.',                                               ingredients: 'Flour, Cocoa, Dark Chocolate, Cream, Butter, Baking Soda', allergens: 'Gluten, Dairy', storage: 'Refrigerate. Best within 2 days.' },
  { id: 21, category: 'eggless',     name: 'Eggless Red Velvet',       subtitle: 'Veg-friendly velvet dream',          price: 849,  originalPrice: 1099, discount: 23, rating: 4.8, reviews: 1876, deliveryTime: '60 min', emoji: '💚', egg: 'Eggless', tag: 'EGGLESS',    weights: ['500g','1Kg','1.5Kg'],       serves: '6–8',  flavor: 'Red Velvet',     desc: 'Classic red velvet without eggs — same velvety texture, same cream cheese bliss, fully vegetarian.',                                        ingredients: 'Red Velvet Flour, Buttermilk, Cocoa, Cream Cheese', allergens: 'Gluten, Dairy', storage: 'Refrigerate. Best within 2 days.' },
];

export const ADDONS = [
  { id: 'message',  label: 'Message on Cake', icon: '✍️', price: 0,   desc: 'Custom text piped on cake' },
  { id: 'candle',   label: 'Candles',          icon: '🕯️', price: 49,  desc: 'Set of 6 premium candles' },
  { id: 'knife',    label: 'Cake Knife',        icon: '🔪', price: 29,  desc: 'Elegant silver knife' },
  { id: 'flower',   label: 'Fresh Flowers',     icon: '💐', price: 149, desc: 'Seasonal fresh flowers' },
  { id: 'card',     label: 'Greeting Card',     icon: '💌', price: 49,  desc: 'Handwritten premium card' },
  { id: 'balloon',  label: 'Balloon Bouquet',   icon: '🎈', price: 99,  desc: '5 helium balloons' },
  { id: 'choco',    label: 'Chocolate Box',     icon: '🍫', price: 199, desc: '12-piece assorted box' },
];

export const DELIVERY_SLOTS = [
  { id: 'std',      label: 'Standard',     time: '4–6 hours',  price: 49,  icon: '📦' },
  { id: 'express',  label: 'Express',      time: '90 minutes', price: 99,  icon: '⚡' },
  { id: 'sameday',  label: 'Same Day',     time: 'By 9 PM',    price: 0,   icon: '🚀' },
  { id: 'midnight', label: 'Midnight',     time: '12 AM–1 AM', price: 149, icon: '🌙' },
  { id: 'fixed',    label: 'Fixed Time',   time: 'You choose', price: 79,  icon: '🕐' },
];

export const OFFERS = [
  { id: 1, title: 'FLAT 20% OFF',  subtitle: 'On all Birthday Cakes',    code: 'BDAY20',   color: '#D97706' },
  { id: 2, title: 'FREE MIDNIGHT', subtitle: 'Free midnight above ₹999', code: 'MIDNIGHT', color: '#C6A769' },
  { id: 3, title: 'BUY 1 GET 1',  subtitle: 'On select cupcake boxes',   code: 'BOGO',     color: '#6B4F3A' },
  { id: 4, title: 'FESTIVAL 30%', subtitle: 'Off on Designer Cakes',     code: 'FEST30',   color: '#2D6A4F' },
];

export const REVIEWS = [
  { id: 1, name: 'Priya Sharma',  city: 'Delhi',     rating: 5, avatar: 'PS', cake: 'Belgian Chocolate Truffle', text: 'Ordered for my husband\'s birthday — absolutely divine! Fresh delivery, stunning presentation. Will definitely order again.' },
  { id: 2, name: 'Arjun Mehta',   city: 'Mumbai',    rating: 5, avatar: 'AM', cake: 'Gold Luxe Cake',            text: 'Blew everyone\'s minds at our anniversary dinner. The gold presentation was truly cinematic. Worth every rupee.' },
  { id: 3, name: 'Sneha Patel',   city: 'Bangalore', rating: 5, avatar: 'SP', cake: 'Unicorn Magic Cake',        text: 'My daughter was in tears of joy. Magical cake, perfect packaging, and on-time delivery!' },
  { id: 4, name: 'Rohit Kumar',   city: 'Hyderabad', rating: 5, avatar: 'RK', cake: 'Red Velvet Love Cake',      text: 'Ordered midnight delivery — arrived at 12:01 AM exactly. Impressive logistics and incredible taste!' },
  { id: 5, name: 'Ananya Singh',  city: 'Pune',      rating: 5, avatar: 'AS', cake: 'Marble Texture Cake',       text: 'My guests thought I got it from abroad. Stunning art, incredible flavour. The team is so talented.' },
  { id: 6, name: 'Vikram Nair',   city: 'Chennai',   rating: 5, avatar: 'VN', cake: 'Rainbow Birthday Cake',     text: 'Fed 15 office colleagues — everyone loved every bite. Premium packaging too. 10/10 experience.' },
];
